spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_example?useSSL=false&serverTimezone=UTC
    username: springuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  session:
    store-type: redis
  redis:
    port: 6379
    database: 0
    host: localhost
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
server:
  tomcat:
    uri-encoding: UTF-8
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 172800