spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    username: springuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  session:
    store-type: redis
  redis:
    port: 6379
    database: 0
    host: localhost
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 172800