package sys.controller;

import sys.entity.User;
import sys.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.HashMap;

@RestController    // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    private UserRepository userRepository; // Which is auto-generated by Spring, we will use it to handle the data

    @GetMapping(path = "/add") // Map ONLY GET Requests
    public Object addNewUser(@RequestParam String name, @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        String[] roles = new String[]{"1111","2222"};
        User n = new User();
        n.setName(name);
        n.setEmail(email);
        n.setRoles(roles);
        userRepository.save(n);

        HashMap<String, String> response = new HashMap<>();
        response.put("results", "success");
        return response;
    }

}